# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          working_directory: ~/devcon
          keys:
            - website-dependencies-{{ checksum "~/devcon/package.json" }}
            - website-dependencies-

      - run: 
          working_directory: ~/devcon
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: website-dependencies-{{ checksum "~/devcon/package.json" }}

      - restore_cache:
          working_directory: ~/devcon/functions
          keys:
            - functions-dependencies-{{ checksum "~/devcon/functions/package.json" }}
            - functions-dependencies-
      
      - run:
          working_directory: ~/devcon/functions
          command: npm install

      - save_cache:
          paths:
            - ~/devcon/functions/node_modules
          key: functions-dependencies-{{ checksum "~/devcon/functions/package.json" }}

      - run: cd ~/devcon/

      # run tests!
      # - run: npm test

      - run:
          working_directory: ~/devcon
          command: touch .env && echo SKIP_PREFLIGHT_CHECK=true > .env

      - run: 
          name: Build
          working_directory: ~/devcon
          command: npm run build

      - run:
          name: Deploy to Firebase
          working_directory: ~/devcon
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
        

workflows:
  version: 2

  deploy:
    jobs:
      - deploy
        # filters:
        #   branches:
        #     only: feature/circle