# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/devcon

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: cd functions && npm install --production && cd ..

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test

      - run: touch .env && echo SKIP_PREFLIGHT_CHECK=true > .env
      - run: npm run build

      - run:
        name: Deploy to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
        

workflows:
  version: 2

  deploy:
    jobs:
      - deploy
        # filters:
        #   branches:
        #     only: feature/circle